language: c
matrix:
  include:
    - compiler: clang
      os: osx
      env: ARCH=native
    - compiler: gcc
      os: osx
      env: ARCH=native
    - compiler: clang
      os: linux
      env: ARCH=native
    - compiler: gcc
      os: linux
      env: ARCH=native
    - compiler: gcc
      os: linux
      env: ARCH=mingw32
    - compiler: gcc
      os: linux
      env: ARCH=mingw64

script:
  "./scripts/travis"
